// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
  docsSidebar: [
    'introduction',
    'podman',
    'first-steps',
    { type: 'category', label: 'Tutorials', items: [{ type: 'autogenerated', dirName: 'tutorials' }] },
    { type: 'category', label: 'Commands', items: [{ type: 'autogenerated', dirName: 'commands' }] },
  ],
};
module.exports = sidebars;
