// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: { 'Docs Navigation': ['introduction', 'commands', 'tutorials'] },
  docsSidebar: [{ type: 'autogenerated', dirName: 'commands' }],
};

module.exports = sidebars;
