name: Bug Report
description: File a bug report.
title: "[Bug]: "
body:
  - type: textarea
    attributes:
      label: Concisely describe the issue
      placeholder: Concisely describe the issue, and what page it is on. Do not use an LLM.
  - type: textarea
    attributes:
      label: Upload screenshots or screen recordings
      placeholder: Add screenshots or screen recordings to help explain your problem.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: LLM Policy
      options:
        - label: This issue is human-written, and follow up comments will also be human-written
          required: true
