name: Feature proposal
description: Propose a feature
title: "[Feature]: "
body:
  - type: textarea
    attributes:
      label: Concisely describe the feature
      placeholder: Concisely describe the feature. Do not use an LLM.
  - type: textarea
    attributes:
      label: Upload screenshots
      placeholder: Add screenshots or proposed mockups (optional).
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: LLM Policy
      options:
        - label: This issue is human-written, and follow up comments will also be human-written
          required: true
