# This workflow does nothing on it's own.  It's intended to be re-used by other
# workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Setup and build

on:
  workflow_call:

jobs:
  setup_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable-cache
      - name: Build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'build'
          path: 'build'
