name: Test build content for pages

on:
  pull_request:

permissions:
  contents: read

jobs:
  setup_and_build:
    uses: ./.github/workflows/setup_and_build.yml
    with:
      base_url: /pr-preview/pr-${{ github.event.number }}/
  test:
    needs: setup_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: 'build'
          path: 'build'
      - name: Ensure index page was build
        run: test -r build/index.html
      - name: Record PR number for the preview workflow
        run: echo '${{ github.event.number }}' > pr-number.txt
      - name: Upload PR number
        uses: actions/upload-artifact@v7
        with:
          name: 'pr-number'
          path: 'pr-number.txt'
